### ISSUE TITLE
Check package functionality

### ISSUE THREAD

**Issue by ngiangre** [AndrewC160/ROMOPOmics#2]
Install R package locally using `devtools::install("/path/to/ROMOPOmics")`, find functionality instructions in README/vignette, and make sure each function runs through and as intended

**Comment by ngiangre** [comment]
seems to not have `cur_group_id()` in the namespace of dplyr which is weird...

**Comment by ngiangre** [comment]
TL;DR doesn't work in vignette from demo

**Comment by AndrewC160** [comment]
Is this using the Docker install? If so I think I built the container with a dplyr version that was updated like 24 hours later, and they've since changed group_index() to cur_group_id() if I'm not mistaken. If it's just the Docker install I can update that.

**Comment by ngiangre** [comment]
No I just installed with devtools::install_github and was going through the Rmd in the demo. I bet if I used to docker container it would work but I think installing the right dplyr version upon installing the repo would be very helpful. But in any case I can use the docker container instead so not the end of the world haha
