### ISSUE TITLE
Optimize  expand_entry_columns()

### ISSUE THREAD

**Issue by ngiangre** [AndrewC160/ROMOPOmics#4]
with the full TCGA data set it takes about 2 minutes to churn out the appropriate OMOP tables. If you have a chance to improve it I would be much obliged!

**Comment by AndrewC160** [comment]
I've got a much simpler methods that doesn't use Reduce() or merge; runs in about 20 seconds on the full TCGA set now. Short version: for each separate observation, make a new table and rbind() them together, THEN pivot_wider().
